import { timeStamp } from "node:console";
import { Schema, model } from "mongoose";

const foodSchema = new Schema(
  {
    name: { type: String, required: true },
    price: { type: Number, required: true },
    image: { type: String, required: true },
    ingredients: { type: String, required: true },
    categoryIds: [
      {
        type: Schema.Types.ObjectId,
        ref: "Category",
        required: true,
      },
    ],
  },
  {
    timestamps: true,
  }
);
export const FoodModel = model("Food", foodSchema);

// [
//   {
//     name: "Cheese Burger",
//     price: "12000",
//     image: "https://source.unsplash.com/600x400/?cheeseburger",
//     ingredients: "Beef, cheese, lettuce, tomato",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Chicken Burger",
//     price: "11000",
//     image: "https://source.unsplash.com/600x400/?chicken,burger",
//     ingredients: "Chicken, mayo, lettuce",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Double Beef Burger",
//     price: "15000",
//     image: "https://source.unsplash.com/600x400/?beef,burger",
//     ingredients: "Double beef, cheese, onion",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Veggie Burger",
//     price: "10000",
//     image: "https://source.unsplash.com/600x400/?veggie,burger",
//     ingredients: "Vegetables, tofu, lettuce",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "BBQ Burger",
//     price: "13000",
//     image: "https://source.unsplash.com/600x400/?bbq,burger",
//     ingredients: "Beef, BBQ sauce, onion",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Spicy Chicken Burger",
//     price: "11500",
//     image: "https://source.unsplash.com/600x400/?spicy,chicken,burger",
//     ingredients: "Spicy chicken, lettuce",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Fish Burger",
//     price: "12500",
//     image: "https://source.unsplash.com/600x400/?fish,burger",
//     ingredients: "Fish fillet, tartar sauce",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Classic Pizza",
//     price: "18000",
//     image: "https://source.unsplash.com/600x400/?pizza",
//     ingredients: "Cheese, tomato sauce",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Pepperoni Pizza",
//     price: "20000",
//     image: "https://source.unsplash.com/600x400/?pepperoni,pizza",
//     ingredients: "Pepperoni, cheese",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "BBQ Chicken Pizza",
//     price: "21000",
//     image: "https://source.unsplash.com/600x400/?bbq,chicken,pizza",
//     ingredients: "Chicken, BBQ sauce",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Margarita Pizza",
//     price: "17000",
//     image: "https://source.unsplash.com/600x400/?margherita,pizza",
//     ingredients: "Mozzarella, basil",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
// {
//   name: "Hawaiian Pizza",
//   price: "19500",
//   image: "https://source.unsplash.com/600x400/?hawaiian,pizza",
//   ingredients: "Ham, pineapple",
//   categoryIds: ["695bcb7ebed0d4b4e4e06853"],
// },
// {
//   name: "French Fries",
//   price: "6000",
//   image: "https://source.unsplash.com/600x400/?french,fries",
//   ingredients: "Potato, salt",
//   categoryIds: ["695bcb7ebed0d4b4e4e06853"],
// },
//   {
//     name: "Cheese Fries",
//     price: "7500",
//     image: "https://source.unsplash.com/600x400/?cheese,fries",
//     ingredients: "Potato, cheese",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Chicken Nuggets",
//     price: "9000",
//     image: "https://source.unsplash.com/600x400/?chicken,nuggets",
//     ingredients: "Chicken, bread crumbs",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Fried Chicken",
//     price: "14000",
//     image: "https://source.unsplash.com/600x400/?fried,chicken",
//     ingredients: "Chicken, spices",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Chicken Wings",
//     price: "13000",
//     image: "https://source.unsplash.com/600x400/?chicken,wings",
//     ingredients: "Chicken wings, sauce",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Caesar Salad",
//     price: "11000",
//     image: "https://source.unsplash.com/600x400/?caesar,salad",
//     ingredients: "Lettuce, chicken, cheese",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Greek Salad",
//     price: "10500",
//     image: "https://source.unsplash.com/600x400/?greek,salad",
//     ingredients: "Vegetables, feta cheese",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Beef Steak",
//     price: "28000",
//     image: "https://source.unsplash.com/600x400/?beef,steak",
//     ingredients: "Beef, pepper, salt",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Grilled Chicken",
//     price: "22000",
//     image: "https://source.unsplash.com/600x400/?grilled,chicken",
//     ingredients: "Chicken, herbs",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Pasta Carbonara",
//     price: "19000",
//     image: "https://source.unsplash.com/600x400/?carbonara,pasta",
//     ingredients: "Pasta, bacon, cream",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Pasta Bolognese",
//     price: "18500",
//     image: "https://source.unsplash.com/600x400/?bolognese,pasta",
//     ingredients: "Pasta, beef sauce",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Seafood Pasta",
//     price: "23000",
//     image: "https://source.unsplash.com/600x400/?seafood,pasta",
//     ingredients: "Shrimp, squid, pasta",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Hot Dog",
//     price: "8000",
//     image: "https://source.unsplash.com/600x400/?hotdog",
//     ingredients: "Sausage, bread",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Chili Hot Dog",
//     price: "9000",
//     image: "https://source.unsplash.com/600x400/?chili,hotdog",
//     ingredients: "Sausage, chili sauce",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Club Sandwich",
//     price: "12500",
//     image: "https://source.unsplash.com/600x400/?club,sandwich",
//     ingredients: "Chicken, bacon, bread",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Tuna Sandwich",
//     price: "11500",
//     image: "https://source.unsplash.com/600x400/?tuna,sandwich",
//     ingredients: "Tuna, mayo",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
//   {
//     name: "Ice Cream",
//     price: "7000",
//     image: "https://source.unsplash.com/600x400/?ice,cream,dessert",
//     ingredients: "Milk, sugar",
//     categoryIds: ["695bcb7ebed0d4b4e4e06853"],
//   },
// ];
